name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.0
  cupertino_icons: ^1.0.6
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.7
  firebase_core: ^2.5.0       # Latest version
  cloud_firestore: ^4.6.0    # Latest version
  firebase_auth: ^4.16.0      # Add if you use Firebase Auth
  connectivity_plus: ^3.0.3
  youtube_player_flutter: ^8.0.0
  provider: ^6.0.5
  firebase_app_check: ^0.2.1+8    # Add if you use Firebase Auth


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/college_logo.jpg
    - assets/images/male.jpg
    - assets/images/bg.jpg
    
